CREATE TABLE users(
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                      name varchar(100) NOT NULL ,
                      email varchar(100) NOT NULL ,
                      age int check ( age>0 )
);

CREATE TABLE books(
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                      user_id int references users(id),
                      book_name varchar(100) NOT NULL ,
                      publish_year int check ( publish_year > 1500 )
);


INSERT INTO users(name, email, age) VALUES ('James Brown', 'james@gmail.com', 27);
INSERT INTO users(name, email, age) VALUES ('John Smith', 'john@gmail.com', 35);
INSERT INTO users(name, email, age) VALUES ('Emily Johnson', 'emily@gmail.com', 42);
INSERT INTO users(name, email, age) VALUES ('Michael Williams', 'michael@gmail.com', 29);
INSERT INTO users(name, email, age) VALUES ('Sophia Anderson', 'sophia@gmail.com', 31);
INSERT INTO users(name, email, age) VALUES ('Daniel Davis', 'daniel@gmail.com', 33);
INSERT INTO users(name, email, age) VALUES ('Olivia Wilson', 'olivia@gmail.com', 28);
INSERT INTO users(name, email, age) VALUES ('William Taylor', 'william@gmail.com', 37);
INSERT INTO users(name, email, age) VALUES ('Emma Jones', 'emma@gmail.com', 25);
INSERT INTO users(name, email, age) VALUES ('David Martinez', 'david@gmail.com', 39);
INSERT INTO users(name, email, age) VALUES ('Ava Anderson', 'ava@gmail.com', 30);
INSERT INTO users(name, email, age) VALUES ('Joseph Thomas', 'joseph@gmail.com', 34);
INSERT INTO users(name, email, age) VALUES ('Mia Garcia', 'mia@gmail.com', 26);
INSERT INTO users(name, email, age) VALUES ('Jacob Hernandez', 'jacob@gmail.com', 32);
INSERT INTO users(name, email, age) VALUES ('Sofia Moore', 'sofia@gmail.com', 36);
INSERT INTO users(name, email, age) VALUES ('Benjamin Clark', 'benjamin@gmail.com', 29);
INSERT INTO users(name, email, age) VALUES ('Isabella Young', 'isabella@gmail.com', 27);
INSERT INTO users(name, email, age) VALUES ('Mason Rodriguez', 'mason@gmail.com', 31);
INSERT INTO users(name, email, age) VALUES ('Charlotte Lee', 'charlotte@gmail.com', 33);
INSERT INTO users(name, email, age) VALUES ('Ethan Walker', 'ethan@gmail.com', 38);


INSERT INTO books(user_id, book_name, publish_year) VALUES (1, 'War and Peace', 1884);
INSERT INTO books(user_id, book_name, publish_year) VALUES (1, 'Anna Karenina', 1877);

INSERT INTO books(user_id, book_name, publish_year) VALUES (2, 'Pride and Prejudice', 1813);
INSERT INTO books(user_id, book_name, publish_year) VALUES (2, 'Sense and Sensibility', 1811);
INSERT INTO books(user_id, book_name, publish_year) VALUES (2, 'Emma', 1815);

INSERT INTO books(user_id, book_name, publish_year) VALUES (3, 'To Kill a Mockingbird', 1960);

INSERT INTO books(user_id, book_name, publish_year) VALUES (3, 'The Great Gatsby', 1925);

INSERT INTO books(user_id, book_name, publish_year) VALUES (4, '1984', 1949);
INSERT INTO books(user_id, book_name, publish_year) VALUES (4, 'Animal Farm', 1945);

INSERT INTO books(user_id, book_name, publish_year) VALUES (5, 'The Catcher in the Rye', 1951);


INSERT INTO books(user_id, book_name, publish_year) VALUES (6, 'To Kill a Mockingbird', 1960);

INSERT INTO books(user_id, book_name, publish_year) VALUES (7, 'Pride and Prejudice', 1813);
INSERT INTO books(user_id, book_name, publish_year) VALUES (7, 'Sense and Sensibility', 1811);

INSERT INTO books(user_id, book_name, publish_year) VALUES (8, 'The Lord of the Rings', 1954);
INSERT INTO books(user_id, book_name, publish_year) VALUES (8, 'The Hobbit', 1937);

INSERT INTO books(user_id, book_name, publish_year) VALUES (9, 'The Chronicles of Narnia', 1950);

INSERT INTO books(user_id, book_name, publish_year) VALUES (10, 'Moby-Dick', 1851);

INSERT INTO books(user_id, book_name, publish_year) VALUES (11, 'The Great Gatsby', 1925);

INSERT INTO books(user_id, book_name, publish_year) VALUES (12, '1984', 1949);
INSERT INTO books(user_id, book_name, publish_year) VALUES (12, 'Animal Farm', 1945);

INSERT INTO books(user_id, book_name, publish_year) VALUES (13, 'Brave New World', 1932);

INSERT INTO books(user_id, book_name, publish_year) VALUES (14, 'The Catcher in the Rye', 1951);

INSERT INTO books(user_id, book_name, publish_year) VALUES (15, 'The Odyssey', 1501);

INSERT INTO books(user_id, book_name, publish_year) VALUES (16, 'The Divine Comedy', 1520);

INSERT INTO books(user_id, book_name, publish_year) VALUES (17, 'War and Peace', 1869);

INSERT INTO books(user_id, book_name, publish_year) VALUES (18, 'Crime and Punishment', 1866);

INSERT INTO books(user_id, book_name, publish_year) VALUES (19, 'The Picture of Dorian Gray', 1890);

INSERT INTO books(user_id, book_name, publish_year) VALUES (20, 'To the Lighthouse', 1927);
